port: 80
healthcheck:
  type: http
  http_path: /api/v1/health

resources:
  request:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 200m
    memory: 200Mi

forward_logs: true
monitoring: true

## only external services
externalDns: hancock-wallet-hub
SSL: true
